services:
  server:
    image: amirowdenis/lib:v0.0.2
    environment:
      - PORT=3000
    ports:
      - 80:3000
    links:
      - mongodb
  counter:
    image: amirowdenis/incr:v0.0.1
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
    ports:
      - 4000:4000
    depends_on:
      - storage
    links: ["server"]
  storage:
    image: redis
    volumes:
      - ./data:/data
  mongodb:
    image:  mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    