services:
  server:
    image: amirowdenis/lib:v0.0.1
    environment:
      - PORT=3000
    ports:
      - 80:3000
    volumes:
      - ./service_1/:/app1
  counter:
    image: amirowdenis/incr:v0.0.1
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
    ports:
      - 4000:4000
    depends_on:
      - storage
    links: ["server"]
  storage:
    image: redis
    volumes:
      - ./data:/data
    