services:
  server:
    build: ./service_1
    environment:
      - PORT=3000
    ports:
      - 80:3000
  counter:
    build: ./service_2
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
    ports:
      - 4000:4000
    depends_on:
      - storage
    links: ["server"]
  storage:
    image: redis
    volumes:
      - ./data:/data
    